name: mongo-express
services:
  mongo0:
    image: mongo
    size: micro
    active: true
    version: latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongo_express0:
    image: mongo_express
    size: pico
    active: true
    version: latest
    depends_on:
      - mongo0
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
