name: phpmyadmin
services:
  mysql0:
    size: mili
    image: mysql
    ports:
      - port: 3306
        type: proxy
        public: false
    active: true
    volume: /var/lib/mysql
    version: latest
    volumes:
      - https://raw.githubusercontent.com/kolserdav/conhos-cli/master/examples/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db_name
  phpmyadmin0:
    size: pico
    image: phpmyadmin
    ports:
      - port: 80
        type: proxy
        public: true
        rewrite: /$2
        location: /das(/|$)(.*) # Run in subPath
    active: true
    version: latest
    environment:
      - PMA_HOST=service-phpmyadmin-mysql0
      - PMA_PORT=3306
      - PMA_ABSOLUTE_URI=https://my-domain.cloud.conhos.ru/das/