name: ruby
services:
  node0:
    image: ruby
    version: latest
    size: nano
    active: true
    git:
      url: https://github.com/kolserdav/conhos-ruby-example.git
      branch: master
      untracked: checkout
    pwd: ./
    ports:
      - port: 3000
        type: proxy
    command: bundle install && ruby server.rb
    environment:
      - PORT=3000
