name: wordpress
services:
  php1:
    image: php
    size: micro
    active: true
    version: 8.4-rc-fpm-bookworm
    pwd: ./
    no_restart: true
    git:
      url: https://github.com/kolserdav/conhos-wordpress
      branch: master
      untracked: checkout
    entrypoint: ['sh', './install-extensions.sh']
    command: php-fpm
    depends_on:
      - mysql0
    ports:
      - port: 9000
        type: php
    environment:
      - PORT=9000
  mysql0:
    image: mysql
    size: mili
    active: true
    version: latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db_name
  ftp0:
    image: ftp
    size: pico
    active: true
    version: latest
    depends_on:
      - php1
    environment:
      - 'FTP_USER_NAME=user'
      - 'FTP_USER_PASS=pass'
