name: wordpress
services:
  php1:
    image: php
    size: nano
    active: true
    version: 8.4-rc-fpm-bookworm
    pwd: ./
    restart: on-failure
    git:
      url: https://github.com/kolserdav/conhos-wordpress
      branch: master
      untracked: checkout
    entrypoint:
      - sh
      - ./entrypoint/install-extensions.sh
      - ./entrypoint/chown.sh
    command: php-fpm
    depends_on:
      - mariadb0
    ports:
      - port: 9000
        type: php
    environment:
      - PORT=9000
  mariadb0:
    image: mariadb
    size: micro
    active: true
    version: latest
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=db_name
  ftp0:
    image: ftp
    size: pico
    active: true
    version: latest
    depends_on:
      - php1
    environment:
      - 'FTP_USER_NAME=user'
      - 'FTP_USER_PASS=pass'
